import React from 'react'
import { View, Text, StyleSheet, Share, Pressable, ScrollView } from 'react-native'
import Svg, { Path } from 'react-native-svg'
import { useNavigation } from '@react-navigation/native'
import { NativeStackNavigationProp } from '@react-navigation/native-stack'
import { RootStackParamList } from '../navigation/AppNavigator'
import { useSessionStore } from '../store/sessionStore'
import { ScreenScaffold, PrimaryButton, OfflineBadge } from '../components/ui'
import { ScreenHeader } from '../components/widgets'
import { colors, type, spacing, radius, shadow } from '../theme/tokens'

type Nav = NativeStackNavigationProp<RootStackParamList, 'Report'>

export default function ReportScreen() {
  const nav = useNavigation<Nav>()
  const { student, session, quizResult } = useSessionStore()

  const shareReport = async () => {
    if (!quizResult || !student) return
    const text = `EduLens Report — ${student.name}
Session: ${session?.topic}
Score: ${quizResult.score}/${quizResult.total} (${Math.round(quizResult.percentage)}%)
Weak Areas: ${quizResult.weakTopics.join(', ') || 'None'}
Strong Areas: ${quizResult.strongTopics.join(', ') || 'None'}
Homework: ${quizResult.homework?.conceptRecap?.slice(0, 100) || 'See app for details'}
Generated by EduLens`
    try {
      await Share.share({ message: text, title: 'EduLens Report' })
    } catch {}
  }

  if (!quizResult) {
    return (
      <ScreenScaffold tint="meadow">
        <ScreenHeader title="Report Card" kicker="NO COMPLETED EXAM" onBack={() => nav.goBack()} />
        <View style={styles.center}>
          <Text style={{ fontSize: 48, marginBottom: 16 }}>📋</Text>
          <Text style={styles.waitTitle}>No Report Prepared</Text>
          <Text style={styles.waitDesc}>
            Submit your active live classroom trivia answers first to compile a detailed report card.
          </Text>
          <PrimaryButton label="Go to Lobby" variant="sky" onPress={() => nav.navigate('Lobby')} style={{ width: '80%' }} />
        </View>
      </ScreenScaffold>
    )
  }

  const { score, total, percentage, weakTopics, strongTopics, topicBreakdown, homework } = quizResult
  const grade = percentage >= 90 ? 'A' : percentage >= 75 ? 'B' : percentage >= 60 ? 'C' : 'D'

  return (
    <ScreenScaffold tint="meadow" scroll={false}>
      <ScreenHeader
        title="Session Report"
        kicker="ACADEMIC REPORT CARD"
        onBack={() => nav.goBack()}
        right={
          <Pressable onPress={shareReport} style={{ padding: 4 }}>
            <Svg width={20} height={20} viewBox="0 0 24 24">
              <Path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8M16 6l-4-4-4 4M12 2v13"
                    stroke={colors.skyDeep} strokeWidth="2.5" fill="none"
                    strokeLinecap="round" strokeLinejoin="round" />
            </Svg>
          </Pressable>
        }
      />

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        {/* Student metadata header */}
        <View style={styles.profileCard}>
          <Text style={styles.studentName}>{student?.name}</Text>
          <Text style={styles.metaText}>Class Session Code: {session?.code}</Text>
          <Text style={styles.metaText}>Topic: {session?.topic}</Text>
          <Text style={styles.metaText}>Report Generated: {new Date().toLocaleDateString()}</Text>
        </View>

        {/* Triple Scores Grid */}
        <View style={styles.scoresGrid}>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreLabel}>SCORE</Text>
            <Text style={styles.scoreValue}>{score}/{total}</Text>
          </View>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreLabel}>PERCENT</Text>
            <Text style={[styles.scoreValue, { color: percentage >= 60 ? colors.sageDeep : colors.error }]}>
              {Math.round(percentage)}%
            </Text>
          </View>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreLabel}>GRADE</Text>
            <Text style={[styles.scoreValue, { color: colors.coralDeep }]}>{grade}</Text>
          </View>
        </View>

        {/* Topic perform list */}
        {Object.keys(topicBreakdown).length > 0 && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Topic Performance</Text>
            {Object.entries(topicBreakdown).map(([topic, pct]) => {
              const pass = (pct as number) >= 60
              const col = pass ? colors.sageDeep : colors.error
              return (
                <View key={topic} style={styles.topicRow}>
                  <Text style={styles.topicName} numberOfLines={1}>{topic}</Text>
                  <View style={styles.track}>
                    <View style={[styles.fill, { width: `${pct}%` as any, backgroundColor: col }]} />
                  </View>
                  <Text style={[styles.pctText, { color: col }]}>{Math.round(pct as number)}%</Text>
                </View>
              )
            })}
          </View>
        )}

        {/* Strengths and Weaknesses side by side */}
        <View style={styles.splitRow}>
          <View style={[styles.card, styles.weakBox, { flex: 1 }]}>
            <Text style={[styles.cardTitle, { color: colors.error }]}>⚠️ Needs Review</Text>
            {weakTopics.length ? (
              weakTopics.map((t: string) => <Text key={t} style={styles.weakChipText}>• {t}</Text>)
            ) : (
              <Text style={styles.emptyText}>None</Text>
            )}
          </View>

          <View style={[styles.card, styles.strongBox, { flex: 1 }]}>
            <Text style={[styles.cardTitle, { color: colors.sageDeep }]}>✅ Mastered</Text>
            {strongTopics.length ? (
              strongTopics.map((t: string) => <Text key={t} style={styles.strongChipText}>• {t}</Text>)
            ) : (
              <Text style={styles.emptyText}>None</Text>
            )}
          </View>
        </View>

        {/* Homework Recap Block */}
        {homework?.conceptRecap && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>📚 Assigned RAG Homework</Text>
            <Text style={styles.hwRecap} numberOfLines={3}>{homework.conceptRecap}</Text>
            <Text style={styles.hwMeta}>
              Includes {homework.followUpQuestions?.length || 0} customized check questions & {homework.revisionTasks?.length || 0} revision items.
            </Text>
            <Pressable onPress={() => nav.navigate('Homework')} style={({ pressed }) => [{ marginTop: spacing.sm, opacity: pressed ? 0.7 : 1 }]}>
              <Text style={styles.hwLink}>View Full Assignment Details →</Text>
            </Pressable>
          </View>
        )}

        <View style={styles.btnColumn}>
          <PrimaryButton
            label="Share Report Card"
            variant="coral"
            onPress={shareReport}
            icon={
              <Svg width={20} height={20} viewBox="0 0 24 24">
                <Path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8M16 6l-4-4-4 4M12 2v13"
                      stroke={colors.white} strokeWidth="2.5" fill="none"
                      strokeLinecap="round" strokeLinejoin="round" />
              </Svg>
            }
          />
          <Pressable onPress={() => nav.navigate('Lobby')} style={({ pressed }) => [styles.backBtn, { opacity: pressed ? 0.7 : 1 }]}>
            <Text style={styles.backBtnText}>Back to Lobby Screen</Text>
          </Pressable>
        </View>

        <OfflineBadge style={{ alignSelf: 'center', marginTop: spacing.md }} />
      </ScrollView>
    </ScreenScaffold>
  )
}

const styles = StyleSheet.create({
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
  },
  waitTitle: {
    fontFamily: type.heading.fontFamily,
    fontSize: 20,
    color: colors.ink,
    marginBottom: 6,
    fontWeight: '700',
  },
  waitDesc: {
    ...type.body,
    color: colors.inkSoft,
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
  scrollContent: {
    paddingBottom: spacing.xl,
  },
  profileCard: {
    backgroundColor: colors.card,
    borderRadius: radius.xl,
    padding: spacing.md,
    marginBottom: spacing.md,
    ...shadow.soft,
    borderWidth: 1.5,
    borderColor: colors.line,
  },
  studentName: {
    fontFamily: type.heading.fontFamily,
    fontSize: 22,
    color: colors.ink,
    marginBottom: 6,
    fontWeight: '700',
  },
  metaText: {
    ...type.small,
    color: colors.inkSoft,
    marginTop: 2,
  },
  scoresGrid: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  scoreBox: {
    flex: 1,
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.sm + 2,
    alignItems: 'center',
    ...shadow.soft,
    borderWidth: 1,
    borderColor: colors.line,
  },
  scoreLabel: {
    ...type.caption,
    color: colors.inkSoft,
    fontSize: 10,
    marginBottom: 4,
  },
  scoreValue: {
    ...type.subhead,
    fontSize: 22,
    color: colors.ink,
    fontWeight: '800',
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: radius.xl,
    padding: spacing.md,
    marginBottom: spacing.md,
    ...shadow.soft,
    borderWidth: 1,
    borderColor: colors.line,
  },
  cardTitle: {
    ...type.subhead,
    color: colors.ink,
    marginBottom: spacing.sm,
    fontWeight: '700',
  },
  topicRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xs,
    gap: spacing.sm,
  },
  topicName: {
    ...type.smallBold,
    color: colors.inkSoft,
    width: 80,
  },
  track: {
    flex: 1,
    height: 8,
    backgroundColor: colors.paperDeep,
    borderRadius: radius.pill,
    overflow: 'hidden',
  },
  fill: {
    height: '100%',
    borderRadius: radius.pill,
  },
  pctText: {
    ...type.smallBold,
    width: 38,
    textAlign: 'right',
  },
  splitRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  weakBox: {
    backgroundColor: '#FAF5F5',
    borderColor: 'rgba(201, 88, 107, 0.15)',
  },
  strongBox: {
    backgroundColor: '#F5FAF6',
    borderColor: 'rgba(92, 138, 98, 0.15)',
  },
  weakChipText: {
    ...type.smallBold,
    color: colors.error,
    marginBottom: 4,
  },
  strongChipText: {
    ...type.smallBold,
    color: colors.sageDeep,
    marginBottom: 4,
  },
  emptyText: {
    ...type.small,
    color: colors.inkFaint,
    fontStyle: 'italic',
  },
  hwRecap: {
    ...type.body,
    fontSize: 14,
    lineHeight: 20,
    color: colors.inkSoft,
  },
  hwMeta: {
    ...type.small,
    color: colors.inkFaint,
    marginTop: 6,
  },
  hwLink: {
    ...type.bodyBold,
    color: colors.skyDeep,
    fontSize: 14,
  },
  btnColumn: {
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  backBtn: {
    alignItems: 'center',
    paddingVertical: 14,
  },
  backBtnText: {
    ...type.bodyBold,
    color: colors.inkSoft,
  },
})
