import React from 'react'
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, Share, Alert } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { useNavigation } from '@react-navigation/native'
import { NativeStackNavigationProp } from '@react-navigation/native-stack'
import { RootStackParamList } from '../navigation/AppNavigator'
import { useSessionStore } from '../store/sessionStore'
import { theme } from '../theme'

type Nav = NativeStackNavigationProp<RootStackParamList, 'Report'>

export default function ReportScreen() {
  const nav = useNavigation<Nav>()
  const { student, session, quizResult } = useSessionStore()

  const shareReport = async () => {
    if (!quizResult || !student) return
    const text = `EduLens Report — ${student.name}
Session: ${session?.topic}
Score: ${quizResult.score}/${quizResult.total} (${Math.round(quizResult.percentage)}%)
Weak Areas: ${quizResult.weakTopics.join(', ') || 'None'}
Strong Areas: ${quizResult.strongTopics.join(', ') || 'None'}
Homework: ${quizResult.homework?.conceptRecap?.slice(0, 100) || 'See app for details'}
Generated by EduLens`
    try {
      await Share.share({ message: text, title: 'EduLens Report' })
    } catch {}
  }

  if (!quizResult) {
    return (
      <SafeAreaView style={s.container}>
        <View style={s.header}>
          <TouchableOpacity onPress={() => nav.goBack()}><Text style={s.back}>← Back</Text></TouchableOpacity>
        </View>
        <View style={s.center}>
          <Text style={{ fontSize: 40 }}>📋</Text>
          <Text style={s.title}>No Report Yet</Text>
          <Text style={s.sub}>Complete a quiz to generate your report</Text>
        </View>
      </SafeAreaView>
    )
  }

  const { score, total, percentage, weakTopics, strongTopics, topicBreakdown, homework } = quizResult
  const grade = percentage >= 90 ? 'A' : percentage >= 75 ? 'B' : percentage >= 60 ? 'C' : 'D'

  return (
    <SafeAreaView style={s.container}>
      <View style={s.header}>
        <TouchableOpacity onPress={() => nav.goBack()}><Text style={s.back}>← Back</Text></TouchableOpacity>
        <Text style={s.headerTitle}>My Report</Text>
        <TouchableOpacity onPress={shareReport}><Text style={s.shareBtn}>Share ↑</Text></TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={s.content}>
        {/* Student info */}
        <View style={s.card}>
          <Text style={s.studentName}>{student?.name}</Text>
          <Text style={s.sessionInfo}>Session: {session?.code} · {session?.topic}</Text>
          <Text style={s.sessionInfo}>Generated: {new Date().toLocaleDateString()}</Text>
        </View>

        {/* Score summary */}
        <View style={s.scoreRow}>
          <View style={s.scoreBox}>
            <Text style={s.scoreLabel}>Score</Text>
            <Text style={s.scoreValue}>{score}/{total}</Text>
          </View>
          <View style={s.scoreBox}>
            <Text style={s.scoreLabel}>Percentage</Text>
            <Text style={[s.scoreValue, { color: percentage >= 60 ? theme.colors.success : theme.colors.danger }]}>{Math.round(percentage)}%</Text>
          </View>
          <View style={s.scoreBox}>
            <Text style={s.scoreLabel}>Grade</Text>
            <Text style={s.scoreValue}>{grade}</Text>
          </View>
        </View>

        {/* Topic breakdown */}
        {Object.keys(topicBreakdown).length > 0 && (
          <View style={s.card}>
            <Text style={s.sectionTitle}>Topic Performance</Text>
            {Object.entries(topicBreakdown).map(([topic, pct]) => (
              <View key={topic} style={s.topicRow}>
                <Text style={s.topicName}>{topic}</Text>
                <View style={s.bar}><View style={[s.barFill, { width: `${pct}%` as any, backgroundColor: (pct as number) >= 60 ? theme.colors.success : theme.colors.danger }]} /></View>
                <Text style={s.topicPct}>{Math.round(pct as number)}%</Text>
              </View>
            ))}
          </View>
        )}

        {/* Weak & Strong */}
        <View style={s.twoCol}>
          <View style={[s.card, { flex: 1, backgroundColor: theme.colors.dangerDim }]}>
            <Text style={s.sectionTitle}>⚠️ Weak</Text>
            {weakTopics.length ? weakTopics.map(t => <Text key={t} style={s.chip}>{t}</Text>) : <Text style={s.none}>None</Text>}
          </View>
          <View style={[s.card, { flex: 1, backgroundColor: theme.colors.successDim }]}>
            <Text style={s.sectionTitle}>✅ Strong</Text>
            {strongTopics.length ? strongTopics.map(t => <Text key={t} style={[s.chip, { color: theme.colors.success }]}>{t}</Text>) : <Text style={s.none}>None</Text>}
          </View>
        </View>

        {/* Homework summary */}
        {homework?.conceptRecap && (
          <View style={s.card}>
            <Text style={s.sectionTitle}>📚 Homework Assigned</Text>
            <Text style={s.bodyText}>{homework.conceptRecap}</Text>
            <Text style={s.hwCount}>
              {homework.followUpQuestions?.length || 0} follow-up questions · {homework.revisionTasks?.length || 0} revision tasks
            </Text>
            <TouchableOpacity onPress={() => nav.navigate('Homework')}>
              <Text style={{ color: theme.colors.primary, fontWeight: '600', marginTop: 8 }}>View full homework →</Text>
            </TouchableOpacity>
          </View>
        )}

        <TouchableOpacity style={s.shareFullBtn} onPress={shareReport}>
          <Text style={s.shareFullBtnText}>📤 Share This Report</Text>
        </TouchableOpacity>

        <TouchableOpacity style={s.homeBtn} onPress={() => nav.navigate('Lobby')}>
          <Text style={s.homeBtnText}>Back to Session</Text>
        </TouchableOpacity>
      </ScrollView>
    </SafeAreaView>
  )
}

const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16, borderBottomWidth: 1, borderBottomColor: theme.colors.border },
  back: { color: theme.colors.primary, fontSize: 16 },
  headerTitle: { fontSize: 16, fontWeight: '700', color: theme.colors.text },
  shareBtn: { color: theme.colors.primary, fontSize: 15, fontWeight: '600' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32, gap: 12 },
  title: { fontSize: 22, fontWeight: '700', color: theme.colors.text },
  sub: { fontSize: 14, color: theme.colors.textMuted, textAlign: 'center' },
  content: { padding: 16, gap: 14 },
  card: { backgroundColor: theme.colors.surface, borderRadius: 16, padding: 18 },
  studentName: { fontSize: 20, fontWeight: '800', color: theme.colors.text, marginBottom: 4 },
  sessionInfo: { fontSize: 13, color: theme.colors.textMuted },
  scoreRow: { flexDirection: 'row', gap: 10 },
  scoreBox: { flex: 1, backgroundColor: theme.colors.surface, borderRadius: 14, padding: 14, alignItems: 'center' },
  scoreLabel: { fontSize: 11, fontWeight: '600', color: theme.colors.textMuted, marginBottom: 6 },
  scoreValue: { fontSize: 24, fontWeight: '800', color: theme.colors.text },
  sectionTitle: { fontSize: 14, fontWeight: '700', color: theme.colors.text, marginBottom: 12 },
  topicRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  topicName: { width: 70, fontSize: 12, color: theme.colors.textSub },
  bar: { flex: 1, height: 7, backgroundColor: theme.colors.border, borderRadius: 4, overflow: 'hidden' },
  barFill: { height: '100%', borderRadius: 4 },
  topicPct: { width: 36, fontSize: 12, fontWeight: '700', textAlign: 'right', color: theme.colors.text },
  twoCol: { flexDirection: 'row', gap: 10 },
  chip: { fontSize: 12, fontWeight: '600', color: theme.colors.danger, marginBottom: 4 },
  none: { fontSize: 12, color: theme.colors.textMuted },
  bodyText: { fontSize: 14, lineHeight: 21, color: theme.colors.text },
  hwCount: { fontSize: 12, color: theme.colors.textMuted, marginTop: 8 },
  shareFullBtn: { backgroundColor: theme.colors.primary, padding: 18, borderRadius: 16, alignItems: 'center' },
  shareFullBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  homeBtn: { padding: 16, alignItems: 'center' },
  homeBtnText: { color: theme.colors.textSub, fontSize: 15 }
})
