import React, { useState, useMemo } from 'react'
import { View, Text, StyleSheet, ScrollView, Pressable, Share } from 'react-native'
import Svg, { Path, Rect } from 'react-native-svg'
import QRCode from 'react-native-qrcode-svg'
import { useNavigation } from '@react-navigation/native'
import { NativeStackNavigationProp } from '@react-navigation/native-stack'
import { RootStackParamList } from '../../navigation/AppNavigator'
import { useSessionStore } from '../../store/sessionStore'
import { useProfileStore, SessionRecord } from '../../store/profileStore'
import { ScreenScaffold, PrimaryButton } from '../../components/ui'
import { ScreenHeader } from '../../components/widgets'
import { colors, type, spacing, radius, shadow } from '../../theme/tokens'

type Nav = NativeStackNavigationProp<RootStackParamList>

function pctColor(pct: number) {
  return pct >= 75 ? colors.sageDeep : pct >= 50 ? colors.gold : colors.error
}
function pctGrade(pct: number) {
  return pct >= 90 ? 'A' : pct >= 75 ? 'B' : pct >= 60 ? 'C' : 'D'
}
function fmtDate(iso: string) {
  try { return new Date(iso).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) } catch { return iso }
}

function SessionReportCard({ rec, onPress, active }: { rec: SessionRecord; onPress: () => void; active: boolean }) {
  const pct = rec.quizPercentage || 0
  const haQuiz = rec.quizScore !== undefined
  return (
    <Pressable
      onPress={onPress}
      style={({ pressed }) => [styles.card, active && styles.cardActive, { opacity: pressed ? 0.9 : 1 }]}
    >
      <View style={styles.cardTop}>
        <View style={[styles.topicIcon, active && { backgroundColor: colors.coralWash }]}>
          <Text style={{ fontSize: 18 }}>📋</Text>
        </View>
        <View style={{ flex: 1 }}>
          <Text style={styles.cardTopic} numberOfLines={2}>{rec.topic || 'Session'}</Text>
          <Text style={styles.cardMeta}>{fmtDate(rec.date)} · {rec.code}</Text>
        </View>
        {haQuiz && (
          <View style={[styles.scorePill, { backgroundColor: pct >= 60 ? colors.sageWash : colors.errorWash }]}>
            <Text style={[styles.scorePillText, { color: pctColor(pct) }]}>{pct}%</Text>
          </View>
        )}
      </View>
      {active && (
        <Text style={styles.tapHint}>▲ Tap to collapse</Text>
      )}
    </Pressable>
  )
}

function ReportDetail({ rec, student }: { rec: SessionRecord; student: any }) {
  const [showQR, setShowQR] = useState(false)
  const pct = rec.quizPercentage || 0
  const haQuiz = rec.quizScore !== undefined

  const qrPayload = useMemo(() => {
    if (!haQuiz) return null
    return JSON.stringify({
      type: 'edulens_report', v: 1,
      student: { id: student?.id, name: student?.name },
      session: { code: rec.code, topic: rec.topic },
      date: rec.date.split('T')[0],
      quiz: { score: rec.quizScore, total: rec.quizTotal, percentage: pct },
      weakTopics: rec.weakTopics || [],
      strongTopics: rec.strongTopics || [],
      topicBreakdown: rec.topicBreakdown || {},
      homework: {
        conceptRecap: rec.homework?.conceptRecap?.slice(0, 200) || '',
        revisionCount: rec.homework?.revisionTasks?.length || 0,
        followUpCount: rec.homework?.followUpQuestions?.length || 0,
      },
    })
  }, [rec])

  const share = async () => {
    if (!haQuiz) return
    const text = [
      `📊 EduLens Report — ${student?.name}`,
      `Session: ${rec.topic} (${rec.code})`,
      `Score: ${rec.quizScore}/${rec.quizTotal} · ${pct}% · Grade ${pctGrade(pct)}`,
      rec.weakTopics?.length ? `⚠️ Review: ${rec.weakTopics.join(', ')}` : '',
      rec.strongTopics?.length ? `✅ Strong: ${rec.strongTopics.join(', ')}` : '',
      rec.homework?.conceptRecap ? `📚 ${rec.homework.conceptRecap.slice(0, 120)}…` : '',
      '\nGenerated by EduLens'
    ].filter(Boolean).join('\n')
    try { await Share.share({ message: text, title: 'EduLens Report' }) } catch {}
  }

  return (
    <View style={styles.detail}>
      {/* Scores */}
      {haQuiz && (
        <View style={styles.scoresRow}>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreLabel}>SCORE</Text>
            <Text style={styles.scoreValue}>{rec.quizScore}/{rec.quizTotal}</Text>
          </View>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreLabel}>PERCENT</Text>
            <Text style={[styles.scoreValue, { color: pctColor(pct) }]}>{pct}%</Text>
          </View>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreLabel}>GRADE</Text>
            <Text style={[styles.scoreValue, { color: pctColor(pct) }]}>{pctGrade(pct)}</Text>
          </View>
        </View>
      )}

      {/* Topics */}
      {rec.topicBreakdown && Object.keys(rec.topicBreakdown).length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Topic Breakdown</Text>
          {Object.entries(rec.topicBreakdown).map(([t, p]) => (
            <View key={t} style={styles.topicRow}>
              <Text style={styles.topicName} numberOfLines={1}>{t}</Text>
              <View style={styles.track}>
                <View style={[styles.fill, { width: `${p}%` as any, backgroundColor: (p as number) >= 60 ? colors.sageDeep : colors.error }]} />
              </View>
              <Text style={[styles.pctTxt, { color: (p as number) >= 60 ? colors.sageDeep : colors.error }]}>{Math.round(p as number)}%</Text>
            </View>
          ))}
        </View>
      )}

      {/* Weak / Strong */}
      {haQuiz && (
        <View style={styles.splitRow}>
          <View style={[styles.section, styles.weakCard, { flex: 1 }]}>
            <Text style={[styles.sectionTitle, { color: colors.error }]}>⚠️ Review</Text>
            {rec.weakTopics?.length
              ? rec.weakTopics.map(t => <Text key={t} style={styles.weakTxt}>· {t}</Text>)
              : <Text style={styles.noneTxt}>None</Text>}
          </View>
          <View style={[styles.section, styles.strongCard, { flex: 1 }]}>
            <Text style={[styles.sectionTitle, { color: colors.sageDeep }]}>✅ Mastered</Text>
            {rec.strongTopics?.length
              ? rec.strongTopics.map(t => <Text key={t} style={styles.strongTxt}>· {t}</Text>)
              : <Text style={styles.noneTxt}>None</Text>}
          </View>
        </View>
      )}

      {/* Homework */}
      {rec.homework?.conceptRecap && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>📚 Homework Recap</Text>
          <Text style={styles.hwText}>{rec.homework.conceptRecap}</Text>
          {(rec.homework.revisionTasks?.length || 0) > 0 && (
            <Text style={styles.hwMeta}>{rec.homework.revisionTasks.length} revision tasks · {rec.homework.followUpQuestions?.length || 0} follow-up questions</Text>
          )}
        </View>
      )}

      {/* QR Export */}
      {qrPayload && (
        <View style={styles.qrCard}>
          <Pressable style={styles.qrToggle} onPress={() => setShowQR(v => !v)}>
            <Svg width={18} height={18} viewBox="0 0 24 24">
              <Rect x="3" y="3" width="8" height="8" rx="1.5" stroke={colors.skyDeep} strokeWidth="2" fill="none" />
              <Rect x="13" y="3" width="8" height="8" rx="1.5" stroke={colors.skyDeep} strokeWidth="2" fill="none" />
              <Rect x="3" y="13" width="8" height="8" rx="1.5" stroke={colors.skyDeep} strokeWidth="2" fill="none" />
              <Path d="M13 17h3M17 13v4M17 17h4M13 13v4" stroke={colors.skyDeep} strokeWidth="2" strokeLinecap="round" />
            </Svg>
            <Text style={styles.qrToggleText}>{showQR ? 'Hide QR Code' : 'Show QR for Teacher'}</Text>
          </Pressable>
          {showQR && (
            <View style={styles.qrBox}>
              <QRCode value={qrPayload} size={160} color={colors.ink} backgroundColor={colors.card} />
              <Text style={styles.qrHint}>Teacher scans this to receive your report</Text>
            </View>
          )}
        </View>
      )}

      {haQuiz && (
        <Pressable onPress={share} style={({ pressed }) => [styles.shareBtn, { opacity: pressed ? 0.7 : 1 }]}>
          <Text style={styles.shareBtnText}>↑ Share Report</Text>
        </Pressable>
      )}
    </View>
  )
}

export default function StudentReportTab() {
  const nav = useNavigation<Nav>()
  const { student, session, quizResult } = useSessionStore()
  const { getActiveProfile, sessionHistory } = useProfileStore()
  const profile = getActiveProfile()
  const [selectedId, setSelectedId] = useState<string | null>(null)

  // Build a unified list: current session result (if any) + history
  const allSessions = useMemo(() => {
    const list: SessionRecord[] = []
    if (quizResult && session) {
      list.push({
        id: `current-${session.id}`,
        sessionId: session.id,
        code: session.code,
        topic: session.topic,
        date: new Date().toISOString(),
        durationSeconds: 0,
        quizScore: quizResult.score,
        quizTotal: quizResult.total,
        quizPercentage: Math.round(quizResult.percentage),
        weakTopics: quizResult.weakTopics,
        strongTopics: quizResult.strongTopics,
        topicBreakdown: quizResult.topicBreakdown,
        homework: quizResult.homework,
        reportId: quizResult.reportId,
      })
    }
    // Add history (deduplicate current session)
    for (const r of sessionHistory) {
      if (session && r.sessionId === session.id && quizResult) continue
      list.push(r)
    }
    return list
  }, [quizResult, session, sessionHistory])

  return (
    <ScreenScaffold tint="meadow" scroll={false} padded={false}>
      <View style={{ paddingHorizontal: spacing.lg }}>
        <ScreenHeader title="My Reports" kicker="REPORT CARD" />
      </View>

      {allSessions.length === 0 ? (
        <View style={styles.empty}>
          <Text style={styles.emptyIcon}>📋</Text>
          <Text style={styles.emptyTitle}>No reports yet</Text>
          <Text style={styles.emptyDesc}>Complete a quiz in a live session and your report will appear here.</Text>
          {session && (
            <PrimaryButton label="Go to Lobby" variant="sky" onPress={() => nav.navigate('Lobby')}
                           style={{ marginTop: spacing.md, width: '80%' }} />
          )}
        </View>
      ) : (
        <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
          {quizResult && session && (
            <View style={styles.activeBanner}>
              <Text style={styles.activeBannerText}>🟢 Active session — {session.topic}</Text>
            </View>
          )}
          {allSessions.map(rec => (
            <View key={rec.id}>
              <SessionReportCard
                rec={rec}
                active={selectedId === rec.id}
                onPress={() => setSelectedId(selectedId === rec.id ? null : rec.id)}
              />
              {selectedId === rec.id && (
                <ReportDetail rec={rec} student={student} />
              )}
            </View>
          ))}
        </ScrollView>
      )}
    </ScreenScaffold>
  )
}

const styles = StyleSheet.create({
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.xl },
  emptyIcon: { fontSize: 52, marginBottom: spacing.md },
  emptyTitle: { ...type.subhead, color: colors.ink, fontWeight: '700', marginBottom: spacing.xs },
  emptyDesc: { ...type.small, color: colors.inkSoft, textAlign: 'center', lineHeight: 20 },
  scroll: { paddingBottom: spacing.xl, paddingHorizontal: spacing.lg },
  activeBanner: {
    backgroundColor: '#E8FFE8', borderRadius: radius.md,
    padding: spacing.xs + 2, marginBottom: spacing.sm,
    borderWidth: 1, borderColor: '#A0E0A0',
  },
  activeBannerText: { ...type.small, color: '#2D6A2D' },
  card: {
    backgroundColor: colors.card, borderRadius: radius.lg,
    padding: spacing.md, marginBottom: 4,
    ...shadow.soft, borderWidth: 1, borderColor: colors.line,
  },
  cardActive: { borderColor: colors.coral, borderWidth: 1.5 },
  cardTop: { flexDirection: 'row', alignItems: 'center' },
  topicIcon: {
    width: 40, height: 40, borderRadius: 12,
    backgroundColor: colors.paperDeep,
    alignItems: 'center', justifyContent: 'center',
    marginRight: spacing.sm,
  },
  cardTopic: { ...type.bodyBold, color: colors.ink },
  cardMeta: { ...type.small, color: colors.inkFaint, marginTop: 2 },
  scorePill: {
    paddingHorizontal: 10, paddingVertical: 4,
    borderRadius: radius.pill, marginLeft: spacing.sm,
  },
  scorePillText: { ...type.caption, fontWeight: '800', fontSize: 13 },
  tapHint: { ...type.caption, color: colors.coralDeep, marginTop: spacing.xs, textAlign: 'center' },
  detail: {
    backgroundColor: colors.paperDeep,
    borderRadius: radius.lg, padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1, borderColor: colors.line,
  },
  scoresRow: { flexDirection: 'row', gap: spacing.xs, marginBottom: spacing.sm },
  scoreBox: {
    flex: 1, backgroundColor: colors.card,
    borderRadius: radius.md, padding: spacing.sm,
    alignItems: 'center', borderWidth: 1, borderColor: colors.line,
  },
  scoreLabel: { ...type.caption, color: colors.inkFaint, fontSize: 10, marginBottom: 3 },
  scoreValue: { ...type.subhead, fontSize: 20, color: colors.ink, fontWeight: '800' },
  section: {
    backgroundColor: colors.card, borderRadius: radius.md,
    padding: spacing.sm, marginBottom: spacing.sm,
    borderWidth: 1, borderColor: colors.line,
  },
  sectionTitle: { ...type.smallBold, color: colors.ink, marginBottom: spacing.xs, fontWeight: '700' },
  topicRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6, gap: spacing.xs },
  topicName: { ...type.small, color: colors.inkSoft, width: 80 },
  track: { flex: 1, height: 7, backgroundColor: colors.paperDeep, borderRadius: radius.pill, overflow: 'hidden' },
  fill: { height: '100%', borderRadius: radius.pill },
  pctTxt: { ...type.smallBold, width: 36, textAlign: 'right', fontSize: 12 },
  splitRow: { flexDirection: 'row', gap: spacing.xs, marginBottom: spacing.sm },
  weakCard: { backgroundColor: '#FAF5F5', borderColor: 'rgba(201,88,107,0.15)' },
  strongCard: { backgroundColor: '#F5FAF6', borderColor: 'rgba(92,138,98,0.15)' },
  weakTxt: { ...type.small, color: colors.error, marginBottom: 3 },
  strongTxt: { ...type.small, color: colors.sageDeep, marginBottom: 3 },
  noneTxt: { ...type.small, color: colors.inkFaint, fontStyle: 'italic' },
  hwText: { ...type.small, color: colors.inkSoft, lineHeight: 20 },
  hwMeta: { ...type.caption, color: colors.inkFaint, marginTop: 6 },
  qrCard: {
    backgroundColor: colors.card, borderRadius: radius.md,
    padding: spacing.sm, marginBottom: spacing.sm,
    borderWidth: 1, borderColor: colors.skyWash,
  },
  qrToggle: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  qrToggleText: { ...type.smallBold, color: colors.skyDeep },
  qrBox: { alignItems: 'center', paddingTop: spacing.sm },
  qrHint: { ...type.caption, color: colors.inkFaint, marginTop: spacing.xs },
  shareBtn: {
    backgroundColor: colors.coralWash, borderRadius: radius.pill,
    padding: spacing.sm, alignItems: 'center',
  },
  shareBtnText: { ...type.smallBold, color: colors.coralDeep },
})
